FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
LABEL main="binokool@mail.ru"
ENV admin="admin"
WORKDIR ./app
COPY published/  ./
#ADD https://raw.githubusercontent.com/discdiver/pachy-vid/master/sample_vids/vid1.mp4 \
#/my_app_directory

